CREATE DATABASE Tienda;

USE Tienda;

CREATE TABLE Productos (
  ProductoID INT PRIMARY KEY AUTO_INCREMENT,
  Codigo VARCHAR(255) UNIQUE NOT NULL,
  Nombre VARCHAR(255) NOT NULL,
  Precio DOUBLE DEFAULT 0,
  Activo BOOLEAN DEFAULT 1
);

CREATE TABLE Clientes (
  ClienteID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(255) UNIQUE NOT NULL,
  Correo VARCHAR(255) UNIQUE NOT NULL,
  Direccion VARCHAR(255) DEFAULT 'SIN DIRECCION',
  Telefono VARCHAR(255) DEFAULT 'SIN TELEFONO'
);


CREATE TABLE Ordenes (
  OrdenID INT PRIMARY KEY AUTO_INCREMENT,
  Folio VARCHAR(255) UNIQUE NOT NULL,
  ClientID INT NOT NULL,
  CarritoID INT NOT NULL
);

CREATE TABLE Carritos (
  CarritoID INT PRIMARY KEY AUTO_INCREMENT,
  ClientID INT
);

CREATE TABLE CarritoProductos (
  CarritoProductosID INT PRIMARY KEY AUTO_INCREMENT,
  CarritoID INT NOT NULL,
  ProductoID INT NOT NULL,
  CantidadID INT DEFAULT 1
);

CREATE TABLE Folios (
  FolioID INT PRIMARY KEY AUTO_INCREMENT,
  Folio VARCHAR(255) UNIQUE NOT NULL,
  FolioPrevio INT UNIQUE NOT NULL
);